// use rabe_bn::{Fr, G1, G2, Gt};
use rand::{self, Rng, RngCore};
use std::time::Instant;

use yao_abe_rust::{AccessNode, AccessStructure, YaoABEPrivate, YaoABEPublic, F, G, S};
// use gpsw06_abe::{GpswAbeCiphertext, GpswAbePrivate, GpswAbePublic, AccessNode, AccessStructure, G1, G2, F, S};
use heapless::{consts, FnvIndexMap, Vec};

const SMPL_CNT: u128 = 100;

type PUBLIC<'a, 'b> = YaoABEPublic<'a, 'b>;
type PRIVATE<'a, 'b> = YaoABEPrivate<'a, 'b>;
type ACCESS_NODE<'a> = AccessNode<'a>;

type PUBLIC_MAP = G;
type PRIVATE_MAP = (F, G);

fn main() {
    let mut rng = rand::thread_rng();

    let system_atts: Vec<&str, S> = Vec::from_slice(&[
        "att01", "att02", "att03", "att04", "att05", "att06", "att07", "att08", "att09", "att10",
        "att11", "att12", "att13", "att14", "att15", "att16", "att17", "att18", "att19", "att20",
        "att21", "att22", "att23", "att24", "att25", "att26", "att27", "att28", "att29", "att30",
    ])
    .unwrap();
    // let access_structure = &[
    //   ACCESS_NODE::Node(2, Vec::from_slice(&[1,2,3,4]).unwrap()),
    //   ACCESS_NODE::Leaf("tum"),
    //   ACCESS_NODE::Leaf("student"),
    //   ACCESS_NODE::Leaf("has_bachelor"),
    //   ACCESS_NODE::Leaf("over21"),
    // ];

    let mut public_map: FnvIndexMap<&str, PUBLIC_MAP, S> = FnvIndexMap::new();
    let mut private_map: FnvIndexMap<&str, PRIVATE_MAP, S> = FnvIndexMap::new();

    // println!("Setup");
    // for i in 1..31 {
    //     let mut us = 0;
    //     for _ in 0..SMPL_CNT {
    //         // rprintln!("starting setup");
    //         let mut public_map: FnvIndexMap<&str, PUBLIC_MAP, S> = FnvIndexMap::new();
    //         let mut private_map: FnvIndexMap<&str, PRIVATE_MAP, S> = FnvIndexMap::new();
    //         let start = Instant::now();
    //         let (private, public) = PRIVATE::setup(&system_atts[..i], &mut public_map, &mut private_map, &mut rng);
    //         us += Instant::now().duration_since(start).as_micros();
    //     }
    //     println!("{};{:?}", i, us / SMPL_CNT);
    // }

    let (private, public) =
        PRIVATE::setup(&system_atts, &mut public_map, &mut private_map, &mut rng);

    // println!("Encrypt");
    let mut data: [u8; 256] = [0; 256];
    rng.fill_bytes(&mut data);

    // let atts = ["att12", "att29", "att07", "att10", "att22", "att24", "att23", "att18", "att08", "att06", "att14", "att11", "att25", "att02", "att09", "att26", "att03", "att20", "att04", "att30", "att01", "att21", "att15", "att19", "att05", "att13", "att17", "att27", "att16", "att28"];
    // for i in 1..31 {
    //     // rprintln!("starting setup");
    //     let mut us = 0;
    //     for _ in 0..SMPL_CNT {
    //         let start = Instant::now();
    //         let ciphertext = public.encrypt(&atts[..i], &mut data, &mut rng).unwrap();
    //         us += Instant::now().duration_since(start).as_micros();
    //     }
    //     println!("{};{:?}", i, us / SMPL_CNT);
    // }

    println!("KeyGen");
    let SET_A: &[AccessStructure] = &[
        &[AccessNode::Leaf("att01")],
        &[
            AccessNode::Node(2, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att01"),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[4, 5]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[3, 8]).unwrap()),
            AccessNode::Leaf("att30"),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[4, 5]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[6, 7]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[3, 10]).unwrap()),
            AccessNode::Leaf("att30"),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[4, 7]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[8, 9]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[3, 10, 11]).unwrap()),
            AccessNode::Leaf("att30"),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[4, 7]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[8, 9]).unwrap()),
            AccessNode::Leaf("att25"),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[3, 10, 11, 12]).unwrap()),
            AccessNode::Leaf("att30"),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[4, 7]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[8, 9]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att10"),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[5, 12, 13, 14]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[6, 9]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[10, 11]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att10"),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[5, 12, 13, 16]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[6, 9]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[10, 11]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Node(1, Vec::from_slice(&[14, 15]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[5, 12, 13, 17]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[6, 9]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Node(2, Vec::from_slice(&[10, 11]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[14, 15, 16]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[5, 13, 14, 18]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[1, 2]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[6, 9]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[10, 11, 12]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[15, 16, 17]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[7, 15, 16, 20]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[17, 18, 19]).unwrap()),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[7, 15, 16, 20, 21]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[17, 18, 19]).unwrap()),
            AccessNode::Leaf("att10"),
        ],
        &[
            AccessNode::Node(2, Vec::from_slice(&[7, 15, 16, 20, 21, 22]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[17, 18, 19]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att17"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[7, 15, 16, 20, 21, 22, 23]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[17, 18, 19]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[7, 15, 18, 22, 23, 24, 25]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[16, 17]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20, 21]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[7, 15, 18, 22, 23, 26, 27]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[16, 17]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20, 21]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Node(2, Vec::from_slice(&[24, 25]).unwrap()),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[7, 15, 18, 22, 23, 27, 28]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[2, 3]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 4]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[5, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[9, 10]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[8, 11]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[12, 13, 14]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[16, 17]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20, 21]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[24, 25, 26]).unwrap()),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[9, 17, 20, 24, 25, 29, 30]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 13]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[14, 15, 16]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[18, 19]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[21, 22, 23]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[26, 27, 28]).unwrap()),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[9, 18, 21, 25, 26, 30, 31]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[27, 28, 29]).unwrap()),
            AccessNode::Leaf("att02"),
        ],
        &[
            AccessNode::Node(3, Vec::from_slice(&[9, 18, 21, 25, 26, 30, 33]).unwrap()),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[27, 28, 29]).unwrap()),
            AccessNode::Leaf("att22"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[31, 32]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 26, 30, 33, 34]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[27, 28, 29]).unwrap()),
            AccessNode::Leaf("att22"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[31, 32]).unwrap()),
            AccessNode::Leaf("att21"),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 26, 30, 33, 36]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[27, 28, 29]).unwrap()),
            AccessNode::Leaf("att22"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[31, 32]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[34, 35]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 26, 30, 35, 38]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[27, 28, 29]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[31, 32]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[33, 34]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[36, 37]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 28, 32, 37, 40]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att28"),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[26, 27]).unwrap()),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[29, 30, 31]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[33, 34]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[35, 36]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[38, 39]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 30, 34, 39, 42]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att28"),
            AccessNode::Node(1, Vec::from_slice(&[26, 27]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[28, 29]).unwrap()),
            AccessNode::Leaf("att08"),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[31, 32, 33]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[35, 36]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[37, 38]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[40, 41]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 25, 30, 36, 41, 44]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 24]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att28"),
            AccessNode::Node(1, Vec::from_slice(&[26, 27]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[28, 29]).unwrap()),
            AccessNode::Leaf("att18"),
            AccessNode::Leaf("att08"),
            AccessNode::Node(2, Vec::from_slice(&[31, 32]).unwrap()),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[33, 34, 35]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[37, 38]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[39, 40]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[42, 43]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 27, 32, 38, 43, 46]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(2, Vec::from_slice(&[24, 25]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[22, 23, 26]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att28"),
            AccessNode::Node(1, Vec::from_slice(&[28, 29]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[30, 31]).unwrap()),
            AccessNode::Leaf("att18"),
            AccessNode::Leaf("att08"),
            AccessNode::Node(2, Vec::from_slice(&[33, 34]).unwrap()),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[35, 36, 37]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[39, 40]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[41, 42]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[44, 45]).unwrap()),
        ],
        &[
            AccessNode::Node(
                4,
                Vec::from_slice(&[9, 18, 21, 29, 34, 40, 45, 48]).unwrap(),
            ),
            AccessNode::Leaf("att12"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att16"),
            AccessNode::Leaf("att30"),
            AccessNode::Node(2, Vec::from_slice(&[3, 4]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[2, 5]).unwrap()),
            AccessNode::Node(2, Vec::from_slice(&[1, 6]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Node(1, Vec::from_slice(&[7, 8]).unwrap()),
            AccessNode::Leaf("att06"),
            AccessNode::Leaf("att25"),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att09"),
            AccessNode::Node(1, Vec::from_slice(&[11, 12, 13]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[10, 14]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att02"),
            AccessNode::Node(2, Vec::from_slice(&[15, 16, 17]).unwrap()),
            AccessNode::Leaf("att23"),
            AccessNode::Leaf("att25"),
            AccessNode::Node(1, Vec::from_slice(&[19, 20]).unwrap()),
            AccessNode::Leaf("att01"),
            AccessNode::Leaf("att11"),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[23, 24]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att11"),
            AccessNode::Node(2, Vec::from_slice(&[26, 27]).unwrap()),
            AccessNode::Node(1, Vec::from_slice(&[22, 25, 28]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Leaf("att28"),
            AccessNode::Node(1, Vec::from_slice(&[30, 31]).unwrap()),
            AccessNode::Leaf("att10"),
            AccessNode::Node(2, Vec::from_slice(&[32, 33]).unwrap()),
            AccessNode::Leaf("att18"),
            AccessNode::Leaf("att08"),
            AccessNode::Node(2, Vec::from_slice(&[35, 36]).unwrap()),
            AccessNode::Leaf("att17"),
            AccessNode::Leaf("att24"),
            AccessNode::Node(3, Vec::from_slice(&[37, 38, 39]).unwrap()),
            AccessNode::Leaf("att21"),
            AccessNode::Leaf("att22"),
            AccessNode::Node(1, Vec::from_slice(&[41, 42]).unwrap()),
            AccessNode::Leaf("att02"),
            AccessNode::Node(1, Vec::from_slice(&[43, 44]).unwrap()),
            AccessNode::Leaf("att07"),
            AccessNode::Leaf("att21"),
            AccessNode::Node(2, Vec::from_slice(&[46, 47]).unwrap()),
        ],
    ];
    let atts = [
        "att12", "att29", "att07", "att10", "att22", "att24", "att23", "att18", "att08", "att06",
        "att14", "att11", "att25", "att02", "att09", "att26", "att03", "att20", "att04", "att30",
        "att01", "att21", "att15", "att19", "att05", "att13", "att17", "att27", "att16", "att28",
    ];

    let ciphertext = public.encrypt(&atts, &mut data, &mut rng).unwrap();

    rng.fill_bytes(&mut data);
    println!("atts;setup;dec");
    for i in 0..SET_A.len() {
        // rprintln!("starting setup");
        let mut keygen_us = 0;
        let mut dec_us = 0;
        for _ in 0..SMPL_CNT {
            let mut data_cpy = data.clone();
            let ciphertext = public.encrypt(&atts, &mut data_cpy, &mut rng).unwrap();

            let start = Instant::now();
            let key = private.keygen(&SET_A[i], &mut rng).unwrap();
            keygen_us += Instant::now().duration_since(start).as_micros();

            let start = Instant::now();
            let data_recovered = YaoABEPublic::decrypt(ciphertext, &key).unwrap();
            dec_us += Instant::now().duration_since(start).as_micros();
            assert_eq!(data_recovered, data);
        }
        println!("{};{};{}", i + 1, keygen_us / SMPL_CNT, dec_us / SMPL_CNT);
    }
    // let access_structure: AccessStructure = &[
    //   AccessNode::Node(2, Vec::from_slice(&[1,2,3,4]).unwrap()),
    //   AccessNode::Leaf("tum"),
    //   AccessNode::Leaf("student"),
    //   AccessNode::Leaf("has_bachelor"),
    //   AccessNode::Leaf("over21"),
    // ];
}
