[package]
name = "nrf52832-test"
version = "0.1.0"
authors = ["Daniel Bücheler <daniel.buecheler@tum.de>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
rtt-target = { version = "0.3.0", features = ["cortex-m"] }
nrf52832-hal = "0.10.0"

