[package]
name = "yao-abe-rust"
version = "0.1.0"
authors = ["Daniel Bücheler <dabch@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rabe-bn = "0.4.12"
rabe = "0.2.4"
rand = "0.7.3"
#aes = "0.6.0"
rust-crypto = "0.2.36"

[dev-dependencies]
criterion = "0.3"



[patch.crates-io]
rabe-bn = { path = "../../rabe-bn-own"}

[[bench]]
name = "deeptree_bench"
harness = false
